version: '3.8'

services:
  my-frontend:
    build:
      context: ./frontend
    container_name: vite
    depends_on:
      - my-java
    ports:
      - "3456:80"
    networks:
      - my-network

  my-java:
    build:
      context: ./backend
    container_name: my-java
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Secret-server
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - my-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: Secret-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

networks:
  my-network: