services:
  - type: web
    name: my-frontend
    runtime: docker
    repo: https://github.com/render-examples/frontend.git
    buildCommand: docker build ./frontend -t my-frontend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:5432/Secret-server
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres

  - type: web
    name: my-java
    runtime: docker
    repo: https://github.com/render-examples/backend.git
    buildCommand: docker build ./backend -t my-java
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:5432/Secret-server
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres

  - type: web
    name: postgres
    runtime: postgres:latest
    buildCommand: docker pull postgres:latest
    startCommand: >
      docker run --network=my-network --name postgres
      -e POSTGRES_DB=Secret-server
      -e POSTGRES_USER=postgres
      -e POSTGRES_PASSWORD=postgres
